/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published blog posts */
        get: operations["BlogController_listBlogs"];
        put?: never;
        /** Create a new blog post */
        post: operations["BlogController_createBlog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blogs/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch author profiles by IDs */
        post: operations["BlogController_getAuthors"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blogs/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List own blog posts */
        get: operations["BlogController_listMyBlogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blogs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a blog post by ID */
        get: operations["BlogController_getBlog"];
        /** Update a blog post */
        put: operations["BlogController_updateBlog"];
        post?: never;
        /** Delete a blog post */
        delete: operations["BlogController_deleteBlog"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List attachments */
        get: operations["AttachmentController_listAttachments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{blogId}/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a presigned upload URL for a blog attachment
         * @description Returns a presigned PUT URL valid for 15 minutes. Upload the file using that URL, then call POST /attachments/:id/sync to register it.
         */
        post: operations["AttachmentController_issueAttachmentUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync a directly-uploaded attachment from R2 into Firestore
         * @description Verifies that the object exists in R2 and then creates the attachment metadata document in Firestore. Use the attachment ID from the upload-url response.
         */
        post: operations["AttachmentController_syncAttachmentFromStorage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{blogId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an attachment */
        post: operations["AttachmentController_createAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an attachment presigned URL */
        get: operations["AttachmentController_getAttachment"];
        /** Update an attachment */
        put: operations["AttachmentController_updateAttachment"];
        post?: never;
        /** Delete an attachment */
        delete: operations["AttachmentController_deleteAttachment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all authors */
        get: operations["AuthorController_listAuthors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an author by ID */
        get: operations["AuthorController_getAuthor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/author": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all authors
         * @deprecated
         */
        get: operations["AuthorLegacyController_listAuthors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/author/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an author by ID
         * @deprecated
         */
        get: operations["AuthorLegacyController_getAuthor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OpenAPI JSON document */
        get: operations["OpenApiController_getDocsJson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/stonemanage/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all games */
        get: operations["StoneManageGamesController_listGames"];
        put?: never;
        /** Create a new game */
        post: operations["StoneManageGamesController_createGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/stonemanage/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game by ID */
        get: operations["StoneManageGamesController_getGame"];
        /** Update a game */
        put: operations["StoneManageGamesController_updateGame"];
        post?: never;
        /** Delete a game and its stones */
        delete: operations["StoneManageGamesController_deleteGame"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/stonemanage/stone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all stones for the user */
        get: operations["StoneManageStonesController_listAllStones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/stonemanage/stone/{gid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new stone in a game */
        post: operations["StoneManageStonesController_createStone"];
        /** Delete all stones in a game */
        delete: operations["StoneManageStonesController_deleteStonesByGame"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/stonemanage/stone/{gid}/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific stone in a game */
        get: operations["StoneManageStonesController_getStone"];
        /** Update a specific stone */
        put: operations["StoneManageStonesController_updateStone"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/stonemanage/stone/{sid}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all logs for a specific stone */
        get: operations["StoneManageLogsController_listLogs"];
        put?: never;
        /** Create a new log for a stone */
        post: operations["StoneManageLogsController_createLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/stonemanage/stone/{sid}/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific log by ID */
        get: operations["StoneManageLogsController_getLog"];
        /** Update an existing log */
        put: operations["StoneManageLogsController_updateLog"];
        post?: never;
        /** Delete a specific log */
        delete: operations["StoneManageLogsController_deleteLog"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/stonemanage/images/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a presigned upload URL for a game or stone image
         * @description Returns a presigned PUT URL valid for 15 minutes. Upload the image using that URL, then pass the returned imageKey when creating or updating a game or stone.
         */
        post: operations["StoneManageImagesController_issueImageUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user profile */
        get: operations["UserController_getProfile"];
        /** Update the authenticated user profile */
        put: operations["UserController_updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete all custom data for the authenticated user */
        delete: operations["UserController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available authentication providers */
        get: operations["ProvidersController_getProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API version */
        get: operations["VersionController_getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/firebase/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Firebase Custom Token for the authenticated user */
        get: operations["FirebaseController_getToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PaginatedBlogResponseDto: {
            data: {
                id: string;
                title: string;
                content: string;
                authorId: string;
                /** @enum {string} */
                status: "archived" | "draft" | "locked" | "published";
                tags: string[];
                createdAt: string;
                updatedAt: string;
                attachments?: {
                    id: string;
                    blogId: string;
                    key: string;
                    contentType: string;
                    size: number;
                    /** @enum {string} */
                    status: "draft" | "published" | "archived" | "locked";
                    authorId: string;
                    createdAt: string;
                    updatedAt: string;
                }[];
            }[];
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        GetAuthorsDto: {
            ids: string[];
        };
        UserResponseDto: {
            id: string;
            name: string | null;
            image: string | null;
        };
        CreateBlogDto: {
            title: string;
            content: string;
            tags?: string[];
            /** @enum {string} */
            status?: "archived" | "draft" | "locked" | "published";
        };
        BlogResponseDto: {
            id: string;
            title: string;
            content: string;
            authorId: string;
            /** @enum {string} */
            status: "archived" | "draft" | "locked" | "published";
            tags: string[];
            createdAt: string;
            updatedAt: string;
            attachments?: {
                id: string;
                blogId: string;
                key: string;
                contentType: string;
                size: number;
                /** @enum {string} */
                status: "draft" | "published" | "archived" | "locked";
                authorId: string;
                createdAt: string;
                updatedAt: string;
            }[];
        };
        UpdateBlogDto: {
            title?: string;
            content?: string;
            tags?: string[];
            /** @enum {string} */
            status?: "archived" | "draft" | "locked" | "published";
        };
        SuccessResponseDto: {
            root?: Record<string, never>;
        };
        AttachmentResponseDto: {
            id: string;
            blogId: string;
            key: string;
            contentType: string;
            size: number;
            /** @enum {string} */
            status: "draft" | "published" | "archived" | "locked";
            authorId: string;
            createdAt: string;
            updatedAt: string;
        };
        CreateAttachmentUploadUrlDto: {
            contentType: string;
        };
        AttachmentUploadUrlResponseDto: {
            /** Format: uri */
            uploadUrl: string;
            attachmentId: string;
            key: string;
            expiresIn: number;
        };
        SyncAttachmentDto: {
            blogId: string;
            /** @enum {string} */
            status?: "archived" | "draft" | "locked" | "published";
        };
        CreateAttachmentDto: {
            /** @enum {string} */
            status?: "archived" | "draft" | "locked" | "published";
        };
        UpdateAttachmentDto: {
            /** @enum {string} */
            status?: "archived" | "draft" | "locked" | "published";
        };
        GameResponseDto: {
            id: string;
            userId: string;
            title: string;
            /**
             * Format: uri
             * @description Signed GET URL for the game image
             */
            image?: string;
            createdAt: string;
            updatedAt: string;
        };
        CreateGameDto: {
            title: string;
            imageKey?: string;
        };
        UpdateGameDto: {
            title?: string;
            imageKey?: string;
        };
        StoneResponseDto: {
            id: string;
            gameId: string;
            userId: string;
            name: string;
            amount: number;
            /**
             * Format: uri
             * @description Signed GET URL for the stone image
             */
            image?: string;
            createdAt: string;
            updatedAt: string;
        };
        CreateStoneDto: {
            name: string;
            amount: number;
            imageKey?: string;
        };
        UpdateStoneDto: {
            name?: string;
            amount?: number;
            imageKey?: string;
        };
        LogResponseDto: {
            id: string;
            stoneId: string;
            userId: string;
            amount: number;
            previousAmount?: number;
            nextAmount?: number;
            createdAt: string;
            updatedAt: string;
        };
        CreateLogDto: {
            amount: number;
        };
        UpdateLogDto: {
            amount?: number;
        };
        CreateImageUploadUrlDto: {
            /**
             * @description The MIME type of the image to be uploaded.
             * @enum {string}
             */
            contentType: "image/jpeg" | "image/png" | "image/webp" | "image/gif";
        };
        ImageUploadUrlResponseDto: {
            /**
             * Format: uri
             * @description The presigned URL to PUT the image to.
             */
            uploadUrl: string;
            /** @description The key referencing the image object in storage. */
            imageKey: string;
            /** @description Number of seconds until the upload URL expires. */
            expiresIn: number;
        };
        UserProfileResponseDto: {
            id: string;
            name: string | null;
            /** Format: email */
            email: string;
            image: string | null;
            username: string | null;
            displayUsername: boolean | null;
            createdAt: string;
            updatedAt: string;
        };
        UpdateUserProfileDto: {
            name?: string;
            /** Format: uri */
            image?: string;
            username?: string;
            displayUsername?: boolean;
        };
        ProvidersResponseDto: {
            /** @description List of available authentication providers */
            providers: {
                /** @description The unique identifier for the provider (e.g., "google", "discord") */
                id: string;
                /** @description The display name for the provider */
                name: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    BlogController_listBlogs: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description asc | desc */
                sort?: string;
                /** @description archived | draft | locked | published */
                status?: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return a list of published blog posts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBlogResponseDto"];
                };
            };
        };
    };
    BlogController_createBlog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBlogDto"];
            };
        };
        responses: {
            /** @description The blog post has been successfully created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogResponseDto"];
                };
            };
        };
    };
    BlogController_getAuthors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetAuthorsDto"];
            };
        };
        responses: {
            /** @description Return author profiles. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    BlogController_listMyBlogs: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description asc | desc */
                sort?: string;
                /** @description archived | draft | locked | published */
                status?: string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return a list of own blog posts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBlogResponseDto"];
                };
            };
        };
    };
    BlogController_getBlog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return a blog post. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogResponseDto"];
                };
            };
        };
    };
    BlogController_updateBlog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBlogDto"];
            };
        };
        responses: {
            /** @description The blog post has been successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlogResponseDto"];
                };
            };
        };
    };
    BlogController_deleteBlog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The blog post has been successfully deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"];
                };
            };
        };
    };
    AttachmentController_listAttachments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return a list of attachments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentResponseDto"][];
                };
            };
        };
    };
    AttachmentController_issueAttachmentUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blogId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttachmentUploadUrlDto"];
            };
        };
        responses: {
            /** @description Presigned upload URL issued successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentUploadUrlResponseDto"];
                };
            };
        };
    };
    AttachmentController_syncAttachmentFromStorage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncAttachmentDto"];
            };
        };
        responses: {
            /** @description Attachment metadata synced to Firestore. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentResponseDto"];
                };
            };
        };
    };
    AttachmentController_createAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blogId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttachmentDto"];
            };
        };
        responses: {
            /** @description The attachment has been successfully created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentResponseDto"];
                };
            };
        };
    };
    AttachmentController_getAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return a presigned URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url?: string;
                        metadata?: components["schemas"]["AttachmentResponseDto"];
                    };
                };
            };
        };
    };
    AttachmentController_updateAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAttachmentDto"];
            };
        };
        responses: {
            /** @description The attachment has been successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentResponseDto"];
                };
            };
        };
    };
    AttachmentController_deleteAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The attachment has been successfully deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"];
                };
            };
        };
    };
    AuthorController_listAuthors: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return a paginated list of authors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    AuthorController_getAuthor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return an author profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    AuthorLegacyController_listAuthors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description [Deprecated] Use GET /authors. Return a list of authors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    AuthorLegacyController_getAuthor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description [Deprecated] Use GET /authors/:id. Return an author profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    OpenApiController_getDocsJson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return the OpenAPI JSON document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"];
                };
            };
        };
    };
    StoneManageGamesController_listGames: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of games for the authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponseDto"][];
                };
            };
        };
    };
    StoneManageGamesController_createGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameDto"];
            };
        };
        responses: {
            /** @description The game has been successfully created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponseDto"];
                };
            };
        };
    };
    StoneManageGamesController_getGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return the game data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponseDto"];
                };
            };
        };
    };
    StoneManageGamesController_updateGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGameDto"];
            };
        };
        responses: {
            /** @description The game metadata has been successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponseDto"];
                };
            };
        };
    };
    StoneManageGamesController_deleteGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The game has been successfully deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"];
                };
            };
        };
    };
    StoneManageStonesController_listAllStones: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns all stones across all games for the authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoneResponseDto"][];
                };
            };
        };
    };
    StoneManageStonesController_createStone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStoneDto"];
            };
        };
        responses: {
            /** @description The stone has been successfully created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoneResponseDto"];
                };
            };
        };
    };
    StoneManageStonesController_deleteStonesByGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The game stones have been successfully deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"];
                };
            };
        };
    };
    StoneManageStonesController_getStone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gid: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return the stone data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoneResponseDto"];
                };
            };
        };
    };
    StoneManageStonesController_updateStone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gid: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStoneDto"];
            };
        };
        responses: {
            /** @description The stone metadata has been successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoneResponseDto"];
                };
            };
        };
    };
    StoneManageLogsController_listLogs: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns all logs for the specified stone. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResponseDto"][];
                };
            };
        };
    };
    StoneManageLogsController_createLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLogDto"];
            };
        };
        responses: {
            /** @description The log has been successfully created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResponseDto"];
                };
            };
        };
    };
    StoneManageLogsController_getLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the specified log. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResponseDto"];
                };
            };
        };
    };
    StoneManageLogsController_updateLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLogDto"];
            };
        };
        responses: {
            /** @description The log has been successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResponseDto"];
                };
            };
        };
    };
    StoneManageLogsController_deleteLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The log has been successfully deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"];
                };
            };
        };
    };
    StoneManageImagesController_issueImageUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImageUploadUrlDto"];
            };
        };
        responses: {
            /** @description Presigned upload URL issued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageUploadUrlResponseDto"];
                };
            };
        };
    };
    UserController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the authenticated user profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponseDto"];
                };
            };
        };
    };
    UserController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserProfileDto"];
            };
        };
        responses: {
            /** @description Returns the updated user profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponseDto"];
                };
            };
        };
    };
    UserController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User data deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProvidersController_getProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return a list of available authentication providers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersResponseDto"];
                };
            };
        };
    };
    VersionController_getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the current version of the API */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FirebaseController_getToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the Firebase Custom Token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token?: string;
                    };
                };
            };
        };
    };
}
